#!/usr/bin/env python

import sys
from uncurl_app import create_app_split_seq
from uncurl_app import cache

app = create_app_split_seq(data_dir=sys.argv[1])
app.config['BOOTSTRAP_SERVE_LOCAL'] = True
app.config['DEPLOY'] = False
app.config['SHOW_ALL_RESULTS'] = True

cache.config = {'CACHE_TYPE': 'simple'}
cache.init_app(app)

app.run()

